load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_binary")

go_library(
    name = "go_default_library",
    srcs = [
        "inflection_map.go",
        "inflection_xml.go",
    ],
    visibility = ["//visibility:public"],
)
